# Generated by Django 2.1 on 2018-09-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('hour', models.CharField(max_length=5)),
                ('delivery_note', models.CharField(max_length=20)),
                ('deliveried', models.BooleanField(default=False)),
                ('sales_order', models.CharField(max_length=20)),
                ('comments', models.TextField()),
            ],
        ),
    ]
