# Generated by Django 2.1 on 2018-09-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='deliveried',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='sales_order',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
