# Generated by Django 2.1 on 2018-09-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20180920_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='deliveried',
            field=models.BooleanField(default=False),
        ),
    ]
